"""Database package exposing connection and all models."""

from .connection import (
    engine,
    async_session_factory,
    get_session,
    get_tenant_session,
)
from .models import (
    Base,
    Tenant,
    User,
    Session,
    AuditLog,
    Institution,
    Department,
    Programme,
    AcademicYear,
    Semester,
    Section,
    Subject,
    Enrollment,
    StaffSubjectAssignment,
    Assignment,
    SubmissionAttempt,
    Rubric,
    RubricCriterion,
    GradeEvent,
)

__all__ = [
    "engine",
    "async_session_factory",
    "get_session",
    "get_tenant_session",
    "Base",
    "Tenant",
    "User",
    "Session",
    "AuditLog",
    "Institution",
    "Department",
    "Programme",
    "AcademicYear",
    "Semester",
    "Section",
    "Subject",
    "Enrollment",
    "StaffSubjectAssignment",
    "Assignment",
    "SubmissionAttempt",
    "Rubric",
    "RubricCriterion",
    "GradeEvent",
]
